name: quartz
description: quartz silverblue image - minimal and bloatware-free

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      - librewolf

    remove:
      - firefox
      - firefox-langpacks
      - gnome-maps
      - gnome-weather
      - gnome-music
      - gnome-photos
      - gnome-tour
      - gnome-contacts
      - gnome-calendar
      - gnome-online-accounts
      - evolution
      - evolution-data-server
      - evolution-devel
      - geary
      - totem
      - rhythmbox
      - baobab
      - gnome-calculator
      - simple-scan
      - gnome-logs
      - yelp
      - tracker-miners
      - tracker
      - at-spi2-core
      - orca
      - speech-dispatcher
      - google-noto-fonts-common
      - google-noto-serif-fonts
      - google-noto-mono-fonts
      - gnome-user-docs
      - fedora-release-notes
      - fprintd
      - cups-pk-helper
      - cups

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user

  - type: signing
